BEGIN EXECUTE IMMEDIATE 'DROP TABLE SavingsAccounts'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Employees'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE BankAccounts'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE SavingsAccounts (
    AccountID NUMBER PRIMARY KEY,
    Balance NUMBER(10, 2)
);
/
INSERT INTO SavingsAccounts VALUES (1, 1000);
INSERT INTO SavingsAccounts VALUES (2, 2000);
INSERT INTO SavingsAccounts VALUES (3, 3000);
COMMIT;
/

CREATE TABLE Employees (
    EmployeeID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Salary NUMBER(10, 2),
    DepartmentID NUMBER
);
/
INSERT INTO Employees VALUES (1, 'Alice', 50000, 10);
INSERT INTO Employees VALUES (2, 'Bob', 60000, 10);
INSERT INTO Employees VALUES (3, 'Charlie', 55000, 20);
COMMIT;
/

CREATE TABLE BankAccounts (
    AccountID NUMBER PRIMARY KEY,
    Balance NUMBER(10, 2)
);
/
INSERT INTO BankAccounts VALUES (101, 5000);
INSERT INTO BankAccounts VALUES (102, 3000);
COMMIT;
/